### ISSUE TITLE
Cool but too slow!

### ISSUE THREAD

**Issue by JuiceLizard** [MLXXXp/FlappyBall#1]
Hi! I am new in Github (but maybe you saw me on arduboy.com?) I like your game but I changed it because I find it too slow. Those are my changes: BALL_ACCELERATION 32, BALLJUMP_VELOCITY (-200), PIPE_MOVE_DISTANCE 4, PIPE_GEN_FRAMES 16 and I shorted the two delay in void deboundeButtons() from 100 to 15. The problem was when I pressed twice the button too fast, the bird jumped just once and I died. Maybe you should use pollButtons() and justPressed() (and no debounce fonction) to fix that issue?

**Comment by MLXXXp** [comment]
Before I made changes, the game was so difficult that it was almost impossible to get past 2 or 3 pipes. It may be too slow for you but I don't want the game to be too difficult for beginners or children, so that they get frustrated. The game won't go on forever because the pipe gap continues to get narrower.

You're welcome to change parameters for your own version of the game but I'm going to leave mine as is. Nobody else has complained about it being too slow.

The _debounceButtons()_ function is only used to start the game after power up, or when toggling sound, or when waiting to continue after displaying the high score. Changing the debounce delays won't affect the handling of the jump button during game play. During game play the jump button auto-repeats so that holding it will cause multiple jumps.
